Queen.destroy_all
Venue.destroy_all


draq_queens = [
  {name: "RuPaul Andre Charles",  drag_name: "RuPaul", hometown: "Atlanta, Georgia" ,img_url: "https://pixel.nymag.com/imgs/fashion/daily/2018/04/24/24-rupaul-makeup.w700.h700.jpg", bio: "RuPaul was born RuPaul Andre Charles on November 17, 1960, in San Diego, California. RuPaul eventually took his cross-dressing persona to stages in Atlanta and New York with bands and as a dancer. In the early 1990s, he landed a record contract and released his first album, Supermodel of the World, while also starting a career in acting. On the strength of his TV shows, including RuPaul's Drag Race, and his oversized personality, RuPaul has become a beacon in gay, drag and transsexual communities."},
  {name: "Roy Haylock", drag_name: "Bianca Del Rio", hometown: "New Orlenas, Louisiana", img_url: "http://outinjersey.net/wp-content/uploads/Bianca_Del_Rio_photo_2_by_Jovanni_Jimenez_Pedraza.jpg", bio: "Haylock grew up in Gretna, Louisiana. He is of Cuban and Honduran descent and is the fourth of five children. He started acting and designing costumes for plays at West Jefferson High School. After high school, he decided to move to New York City and worked at Bloomingdale's for nine months before returning to Louisiana."},
  {name: "Christopher Hardwell", drag_name: "Bob the Drag Queen", hometown:"Columbus, Georgia", img_url: "https://pbs.twimg.com/media/DSYP6pgUEAA9fQM.jpg", bio: "Caldwell started doing drag after watching the first season of RuPaul's Drag Race. Since his first presentations, his character was focused on stand-up comedy routines, and he started lip-syncing after a couple of months into his drag. His initial stage name was Kittin Withawhip, and he was featured in Leland Bobbé's Half Drag Series with this name. In 2013, Caldwell changed his stage name to Bob the Drag Queen."},
  {name: "Alexander Hedges Steinberg", drag_name: "Sasha Velour", hometown: "Berkley, California", img_url: "https://assets.teenvogue.com/photos/5b33e5c8330f9550cdec7b08/16:9/w_1280,c_limit/VIN_1894.jpg", bio: "Steinberg's drag career as Sasha Velour started in Vermont while at school. Known for being an out of the box artist, Steinberg incorporates that eccentricity into Velour's drag persona. Steinberg starred in the music video C.L.A.T. along with fellow New York City drag queens Peppermint, Aja and Alexis Michelle, who also appeared on the ninth season of RuPaul's Drag Race. Velour's makeup and look transformations have been featured in publications such as Vogue,Cosmopolitan, Vanity Fair, and Billboard. Steinberg has further created, produced, and organized different photoshoots, collages, and drawings that discuss art and drag."},
  {name: "Matthew James Lent", drag_name: "Pearl Liaison", hometown: "St. Petersburg, Florida", img_url: "https://i2.wp.com/boyz.co.uk/wp-content/uploads/2018/04/OMG-Pearl-copy-big.png?resize=450%2C270", bio: "After moving to Chicago, Lent began performing in drag in 2012, alongside Kim Chi, using the stage name Pearl.He has described Pearl's persona as a 'stepford wife robot bitch'. Lent initially only planned to use drag as a hobby, but quickly began booking gigs at increasing frequency. He later moved to Brooklyn, New York"},
  {name: "Dustin Winters", drag_name: "Ivy Winters", hometown: "New York, New York", img_url: "http://static.dragnearyou.com/performers/1.1/ivy-winters.png", bio: "Winters was born in 1991. Before Drag Race, he worked as a circus performer for eight and a half years in New York,[where he learned how to juggle, walk on stilts and breathe fire. He started doing drag at 18. He was a costume designer for Lady Bunny and season three contestant Manila Luzon. He came out as gay to his parents at his Freshman year of High School. His sister came out as a lesbian a year later. His brother came out the following year."},
  {name: "Osmund Vacious", drag_name: "Vivacious", hometown: "New York, New York", img_url: "https://pbs.twimg.com/profile_images/416698716591251456/iNwiPO5n_400x400.jpeg", bio: "Vivacious appeared on the sixth season of RuPaul's Drag Race. She 'made one of the most unforgettable first episode entrances in Drag Race herstory', according to The Advocate, by wearing an outfit featuring a second head Vivacious called Ornacia. In 2015, Sadie Gennis of TV Guide ranked Vivacious number 22 in her list of 'The 24 Best RuPaul\'s Drag Race Entrances of All Time', and Time Out's Ethan LaCroix and Jillian Anthony ranked her number eleven on their list of the best Drag Race contestants from New York City. Vivacious ranked number 91 in Vulture\'s list of 'The 100 Greatest RuPaul's Drag Race Looks of All Time.'"},
  {name: "Jaremi Carey", drag_name: "Phi Phi O'Hara", hometown: "Chicago, Illinois", img_url: "https://www.pride.com/sites/www.pride.com/files/2016/09/20/phi-phi-ohara.jpg", bio: "Carey as Phi Phi O'Hara was announced as one of the thirteen contestants for RuPaul's Drag Race season 4 on November 13, 2011. He achieved a runner-up position alongside Chad Michaels and lost to Sharon Needles. He came back for RuPaul's Drag Race All Stars season 2 in 2016 and initially made it to top 5, but after the return of two previously eliminated contestants placed seventh overall."},
  {name: "Junstin Andrew Honard", drag_name: "Alaska", hometown: "Erie, Pennsylvania", img_url: "https://pixel.nymag.com/imgs/daily/vulture/2016/10/14/14-alaska-thunderfvck-drag-race-chat-room-silo.w710.h473.2x.jpg", bio: "Since appearing on RuPaul\'s Drag Race, Alaska has toured and performed, appearing in RuPaul\'s Drag Race Battle of the Seasons shows, the Drag Stars at Sea cruises, custom one-woman shows such as a Stevie Nicks tribute called 'Stevie Forever', a cabaret show called 'Red for Filth', and a holiday show called 'Blue Christmas'. An animated version of Alaska appeared in the 'RuPaul\'s Drag Race: Dragopolis 2.0' mobile app. During the summer of 2014, she starred in a stage production of Sex and the City. With brother Cory Binney, Honard has a web series sponsored by World of Wonder, called Bro\'Laska. In 2014, Alaska became a spokesmodel for American Apparel alongside Willam Belli and Courtney Act."},
  {name: "Justin Dewayne Lee Johnson", drag_name: "Alyssa Edwards", hometown: "Dallas, Texas", img_url: "https://vignette.wikia.nocookie.net/logosrupaulsdragrace/images/e/ef/AlyssaAS2.jpg", bio: "She performs under the stage name Alyssa Edwards. She chose her name in homage to Alyssa Milano and to her drag mother Laken Edwards, a former drag queen. She is part of the drag family 'the Haus of Edwards' and serves as drag mother to fellow RuPaul\'s Drag Race contestants Shangela Laquifa Wadley, Laganja Estranja, Gia Gunn, and Plastique Tiara. She was one of the judges of the 2010 California Entertainer of the Year pageant, which Shangela won."},
  {name: "Martin Cooper", drag_name: "Coco Montrese", hometown: "Las Vegas, Nevada", img_url: "https://vignette.wikia.nocookie.net/logosrupaulsdragrace/images/6/6a/CocoAS2.jpg/revision/latest?cb=20160617131458", bio: "Montrese was chosen to appear on RuPaul\'s Drag Race: All Stars season 2, which premiered August 25, 2016. It was rumored that she was a replacement for Laganja Estranja, but when asked Montrese stated, 'I don't know anything about that.' Montrese was the first contestant cut from the show, being eliminated by Roxxxy Andrews. When asked who should have appeared on the season who was not cast, Montrese stated 'Trixie Mattel ― I think she’s the life of the party. I love Trixie Mattel, she was so funny on her season and I would love to see her there.' Alaska Thunderfuck ended up taking the crown."},
  {name: "Sang-Young Shin", drag_name: "Kim Chi", hometown: "Chicago, Illinois", img_url: "https://nightout.s3.amazonaws.com/media/posters/41056/large-90a968f085be3d9f.jpg?1513713145", bio: "After Drag Race, Kim Chi partnered with Sugarpill Cosmetics to create different makeup items, including the Kim Chi Liquid Lip Color, a donut-scented lipstick described as a 'Matte lavender mauve with a subtle, unique blend of transparent aqua and violet sparkles'. Other items included the Kim Chi Electric Teal Eyeshadow and Kim Chi Liquid Lip Color."}
]

draq_queens.each {|queen| Queen.create(queen)}

venues = [
  {name: "Therapy" , location: "348 W 52nd St, New York, NY 10019", img_url: "https://fastly.4sqi.net/img/general/width960/56138417_dM-6UEG9r29fvq-4q-nKyhVhnhVzCx3j6bMeIKPIOPc.jpg"},
  {name: "Barracuda" , location: "275 W 22nd St, New York, NY 10014", img_url: "https://irs3.4sqi.net/img/general/width700/21891000_57cQ32uKLuWMKvfV4xoEkqipllSsaEpM4GVkpGVIX54.jpg"},
  {name: "Pieces" , location: "8 Christopher St, New York, NY 10014", img_url: "https://fastly.4sqi.net/img/general/width960/64BL7hO3HIio35HXSd3xntDiPlKF0g7bQ70_UHVVYGY.jpg"},
  {name: "Metropolitan" , location: "559 Lorimer St, Brooklyn, NY 11211", img_url: "https://s3-media3.fl.yelpcdn.com/bphoto/7aYdX8RvWtHj2LGh20J07Q/o.jpg"},
  {name: "Ritz Bar and Lounge" , location: "3975, 369 W 46th St, New York, NY 10036", img_url: "https://static1.squarespace.com/static/587fd9153e00be6f0d1fd83e/58f61a1b440243d19ab337c0/58f61b2e46c3c41a505dcab1/1492523822776/The+Ritz+exterior.jpg"},
  {name: "Hardware" , location: "697 10th Ave, New York, NY 10036", img_url: "https://www.travelgay.com/wp-content/uploads/2018/12/hardware-bar-new-york-gay-bar-main.jpg"},
  {name: "Industry" , location: "355 W 52nd St, New York, NY 10019", img_url: "https://d33hncv3fqajvb.cloudfront.net/qgtA3K5E0EF4-5SXAXPZ6L8FwLU=/480x0/filters:quality(70)/location_photos/data/12897/original/industry-bar-new-york-1513682262.jpeg"},
  {name: "Rosemont" , location: "63 Montrose Ave, Brooklyn, NY 11206", img_url: "http://bedfordandbowery.com/wp-content/uploads/2016/04/DRC7499.jpg"},
  {name: "Icon Bar" , location: "31-84 33rd St, Astoria, NY 11106", img_url: "https://pbs.twimg.com/profile_images/848922509521149953/RfhdbZ8__400x400.jpg"}
]

venues.each {|venue| Venue.create(venue)}
